### ISSUE TITLE
Navigation Bar covers the Launch Screen when storyboard entrypoint is a navigation controller

### ISSUE THREAD

**Issue by kishykumar** [granoff/LaunchScreen#1]
I have a navigation controller as the storyboard entry point. 
When I add the launch screen subview, it shows the navigation bar above the launch screen.

Any suggestions how to fix it?

**Comment by granoff** [comment]
You can insert your launch screen view as a subview of your AppDelegate's `window`, something like

```
[[[[UIApplication sharedApplication] delegate] window] insertSubview: ... atIndex:0]
```

Remember that your main view controller's view is simply a subview of the main window (which is just a UIView anyway). There is no problem adding views directly into the window.

The `addSubview:` method generally does insert at index 0, but for the sake of clarity I often use `insertSubview:atIndex:` instead.

**Comment by kishykumar** [comment]
Thanks. That works. 👍 

I know it may not be the right place to ask the following question. Appreciate for the help! 

I want to transition from the Launch Screen to either a LoginViewController or MainViewController depending upon the login state of the user. How to achieve that? 

I can not 'segue' to those view controllers after I remove the launchView because there is some animation/glitch involved in segueing.

**Comment by kishykumar** [comment]
Thanks. That works. 👍
